name: EconomyPlugin
version: '1.0.0'
main: com.minecraft.economy.core.EconomyPlugin
api-version: '1.20'
depend: [Vault]
authors: [Manus]
description: Plugin de economia com sistema de shop dinâmico, loteria, dinheiro rotativo e lojas de jogadores
commands:
  money:
    description: Gerencia o dinheiro dos jogadores
    usage: /money [pay <jogador> <quantia> | top]
    aliases: [bal, balance, saldo]
  eco:
    description: Comandos administrativos de economia
    usage: /eco [give|take|set|reset] <jogador> <quantia>
    permission: economy.admin
    aliases: [ecoadmin]
  shop:
    description: Abre a interface de shop do servidor
    usage: /shop
    aliases: [loja]
  tax:
    description: Gerencia impostos e configurações econômicas
    usage: /tax [set|enable|disable|apply|info] <tipo> <valor>
    permission: economy.admin
  lottery:
    description: Sistema de loteria do servidor
    usage: /lottery [buy|tickets|draw|help]
    aliases: [loteria]
  pay:
    description: Transfere dinheiro para outro jogador
    usage: /pay <jogador> <quantia>
    permission: economy.money.pay
  playershop:
    description: Sistema de lojas de jogadores
    usage: /playershop [create|list|open|add|remove|setprice|withdraw|help]
    aliases: [pshop, lojap]
permissions:
  economy.admin:
    description: Permite acesso a comandos administrativos
    default: op
  economy.money.pay:
    description: Permite transferir dinheiro para outros jogadores
    default: true
  economy.money.top:
    description: Permite ver o ranking de jogadores mais ricos
    default: true
  economy.playershop.use:
    description: Permite usar lojas de jogadores
    default: true
  economy.playershop.create:
    description: Permite criar lojas de jogadores
    default: true
  economy.playershop.admin:
    description: Permite administrar lojas de jogadores
    default: op
