name: EconomyPlugin
version: '1.0.0'
main: com.minecraft.economy.core.EconomyPlugin
api-version: '1.20'
depend: [Vault]
authors: [Manus]
description: Plugin de economia com sistema de shop dinâmico, loteria e dinheiro rotativo
commands:
  money:
    description: Gerencia o dinheiro dos jogadores
    usage: /money [pay <jogador> <quantia> | top]
    aliases: [bal, balance, saldo]
  eco:
    description: Comandos administrativos de economia
    usage: /eco [give|take|set|reset] <jogador> <quantia>
    permission: economy.admin
  shop:
    description: Abre a interface de shop do servidor
    usage: /shop
    aliases: [loja]
  tax:
    description: Gerencia impostos e configurações econômicas
    usage: /tax [set|enable|disable|apply|info] <tipo> <valor>
    permission: economy.admin
  lottery:
    description: Sistema de loteria do servidor
    usage: /lottery [buy|tickets|draw|help]
    aliases: [loteria]
permissions:
  economy.admin:
    description: Permite acesso a comandos administrativos
    default: op
  economy.money.pay:
    description: Permite transferir dinheiro para outros jogadores
    default: true
  economy.money.top:
    description: Permite ver o ranking de jogadores mais ricos
    default: true
